Update installer

diff --git a/testing/iso/rootfs/usr/bin/installer b/testing/iso/rootfs/usr/bin/installer
--- a/testing/iso/rootfs/usr/bin/installer
+++ b/testing/iso/rootfs/usr/bin/installer
@@ -10,19 +10,15 @@ RESET_COLOR="\e[0m"
 
 IS_EFI=1
 SWAPUSED=0
+CORRECTDISK=0
 OLD_PASSWORD=""
-SALT="75vv97x9QnG9MjVR"
-PARTITIONS=$(cat /proc/partitions | awk 'NR > 2 && $4 !~ /^(sr0|loop0)$/ { print $4 }')
-partition_list=()
-while read -r line; do
-    size=$(echo "$line" | awk '{ print $2 }')
-    partition_list+=("$size" "")
-done <<< "$partitions"
+partition_list=($(lsblk -nr -o NAME,TYPE | awk '$2 == "disk" {print "/dev/" $1}'));
 WIRELESS=0
 declare -A AVAILIBLE_LANGUAGES=(
 	[1]=en-US
 	[2]=fr-FR
 )
+
 
 log() {
 	echo -e "[${BOLD_BLUE}LOG${RESET_COLOR}] $*"
@@ -70,69 +66,64 @@ function INFORMATIONS {
 
 # - - - - - - - - - - - - - #
 
+
+function get_password {
+	log "Getting password"
+	password="$(dialog --insecure --passwordbox "Enter machine password:" 0 0 --stdout)"
+
+	# Set new root password
+	log "Setting password..."
+	[[ -n "${password}" ]] || echo -e "${OLD_PASSWORD}\n{password}\n{password}" | passwd
+	log "Password set"
+}
+
+
 function get_language {
 	log "Getting language"
 
-	language=$(dialog --radiolist "Select system language:" 0 0 0 \
-		1 "en-US" on \
-		2 "fr-FR" off \
-		--stdout
-	)
+	language="$(dialog --title "Dialog title" --inputbox "Enter language name (fr / us):" 0 0 --stdout)"
+        if [[ ! -n "${language}" ]]; then
+	    loadkeys ${language}
+            log "Language set to '${language}'"
+        else
+            log "Empty output, US by default.."
+	    sleep 2
+        fi
 
-	case "${language}" in
-		"en-US") loadkeys fr;;
-		"fr-FR") loadkeys us;;
-		*) ;;
-	esac
-
-	log "Language set to '${language}'"
 }
 
 function get_informations {
-	exec 3>&1
-
-	GLOBALVALUES=$(dialog --ok-label "Valider" \
-               --backtitle "System informations" \
-               --title "Enter the informations" \
-               --form "System informations" \
-               15 50 0 \
-               "Machine Name:" 1 1 "${machine_name}" 1 17 30 0 \
-               "Username:" 2 1 "${user_name}" 2 17 30 0 \
-               "Root Password:" 3 1 "${password}" 3 17 30 0 \
-               2>&1 1>&3)
-
-	exec 3>&-
-	machine_name=$(echo "${GLOBALVALUES}" | awk -F: '{print $1}')
-	username=$(echo "${GLOBALVALUES}" | awk -F: '{print $2}')
-	password=$(echo "${GLOBALVALUES}" | awk -F: '{print $3}')
-        password_encrypted=$(mkpasswd -m sha-512 ${password} ${SALT})
-        password_only=$(${password_encrypted} | sed 's/^.*$6$[^$]*$//')
-        username_encrypted="${username}:x:2130:2130:The Guest:/home/${username}:/bin/bash"
+	log "Getting machine name"
+	machine_name="$(dialog --title "System informations" --inputbox "Enter machine name:" 0 0 --stdout)"
+        username="$(dialog --title "System informations" --inputbox "Enter your username:" 0 0 --stdout)"
+        password="$(dialog --title "System informations" --insecure --passwordbox "Enter machine password" 0 0 --stdout)"
 }
 
 
 function configure_network {
-	if dialog --yesno "Does the system use Wireless connection?" 0 0 --stdout; then
+	if dialog --yesno "Does the system should use Wireless connection?" 0 0 --stdout; then
             WIRELESS=1
 	    log "Configuring network"
 
 	    log "Getting network name and password"
-	    network_name="$(dialog --title "Dialog title" --inputbox "Enter network name:" 0 0 --stdout)"
-	    network_password="$(dialog --insecure --passwordbox "Enter network password:" 0 0 --stdout)"
+	    network_name="$(dialog --title "Network name" --inputbox "Enter network name:" 0 0 --stdout)"
+	    network_password="$(dialog --title "Network password" --insecure --passwordbox "Enter network password:" 0 0 --stdout)"
 
-	    # Activating wireless interface
 	    log "Configuration of the network."
 
 	    sudo ifconfig wlp3s0 up
 	    sudo wpa_passphrase WLAN_NAME WLAN_PASSWORD > /etc/wpa_supplicant.conf
 
-	    log "Connecting to network"
+	    log "Configuration to network"
 	    wpa_supplicant -B -i wlp3s0 -c /etc/wpa_supplicant.conf -D wext
      	    mkdir "/root/installdir"
             mv "/etc/unusedwireless" "/root/installdir/25-wireless.network"
-	    log "Network configured. Reboot necessary."
+	    log "Network configured"
+            sleep 2
         else
             rm -f "/etc/unusedwirless"
+	    log "Network configured"
+            sleep 2
         fi
 }
 
@@ -156,20 +147,44 @@ function GET_USER_INFOS {
 #		DISK PARTITION		#
 
 function DISK_PARTITION {
-    section "DISK PARTITIONNING"
-
-    chosen_partition=$(dialog --stdout --menu "Choose the system partition" 15 60 10 "${partition_list[@]}")
-    chosen_partition_size=$(lsblk -b -n -o SIZE -d "${chosen_partition}" | awk '{printf "%.2f", $1 / (1024 * 1024 * 1024)}')
-    if [ "${chosen_partition_size}" -ge "25.00" ]; then
+        clear
+        section "DISK PARTITIONNING"
+        log "Enter your system partition \nhere the list of your partitions: ${partition_list[@]}"
+        echo -n "Input: "
+        read chosen_partition
+        for item in "${partition_list[@]}"; do
+            if [[ "$item" == "${chosen_partition}" ]]; then
+                CORRECTDISK=1
+                break
+            fi
+        done
+    
+        if [[ ${CORRECTDISK} == 0 ]]; then
+            log "Error: System disk not found.."
+	    sleep 2
+            DISK_PARTITION
+        fi
+	
         if dialog --yesno "Do you want to create a swap partition?" 25 85 --stdout; then
-	    SWAPUSED=0
             for i in "${!partition_list[@]}"; do
                 if [ "${partition_list[i]}" = "${chosen_partition}" ]; then
                    unset 'partition_list[i]'
                    break
                 fi
             done
-            swap_partition=$(dialog --stdout --menu "Choose the swap partition" 15 60 10 "${partition_list[@]}")
+	    clear
+	    log "Enter your swap partition \nhere the list of your partitions: ${partition_list[@]}"
+    	    echo -n "Input: "
+   	    read swap_partition
+	    for item in "${partition_list[@]}"; do
+    		if [[ "$item" == "${swap_partition}" ]]; then
+                      SWAPUSED=1
+                      break
+                fi
+            done
+	    if [[ ${SWAPUSED} == 0 ]]; then
+                log "Error: The SWAP will not be used.. Bad values"
+            fi
         fi
     
         if [ -d /sys/firmware/efi ]; then
@@ -180,21 +195,38 @@ function DISK_PARTITION {
                         break
                     fi
                 done
-		efi_partition=$(dialog --stdout --menu "Choose the swap partition" 15 60 10 "${partition_list[@]}")
-                IS_EFI = 0
+		clear
+	        log "Enter your EFI partition \nhere the list of your partitions: ${partition_list[@]}"
+    	        echo -n "Input: "
+   	        read efi_partition
+		efi_partition_size_kb=$(df -k --output=size "${efi_partition}" | tail -n 1)
+    	   	efi_partition_size_gb=$((efi_chosen_partition_size_kb / 1048576))
+		for item in "${partition_list[@]}"; do
+    		    if [[ "$item" == "${efi_partition}" ]]; then
+                        IS_EFI=0
+			if [ "3" -ge "${efi_partition_size_gb}" ]; then
+                            IS_EFI=2
+                        fi
+                        break
+                    fi
+                done
+	        if [[ ${IS_EFI} == 2 ]]; then
+                    log "Error: EFI will not be used.. Not enough space"
+                fi
+		
+		if [[ ${IS_EFI} == 1 ]]; then
+                   log "Error: EFI will not be used.. Bad values"
+                fi
             fi
         fi
-    else
-	dialog --msgbox "Error. The chosen partition is too little to contain the system. 25GB at least." 15 100
-        unset chosen_partition chosen_partition_size
-	DISK_PARTITION
-    fi
 }
 
 function DISK_INSTALL {
     section "INSTALL DISK"
-
-    mkfs.ext4 ${chosen_partition}
+    mkdir -p "/mnt/install"
+    mkdir -p "/mnt/efi"
+    mkdir -p "/mnt/temp"
+    mkfs.ext4 -F ${chosen_partition}
 }
 
 #		GRUB CONFIGURATION		#
@@ -204,52 +236,75 @@ function GRUB_CONF {
 
 
     if [ IS_EFI = 1 ]; then
-        mainPartitionUuid=$(blid ${chosen_partion})
+        mainPartitionUuid=$(blkid ${chosen_partion})
 	if [ SWAPUSED = 0 ]; then
-	    swapPartitionUuid=$(blid ${swap_partion})
+	    swapPartitionUuid=$(blkid ${swap_partion})
         fi
 	mkdir /mnt/install/boot
         grub-install --root-directory=/mnt/install/boot ${chosen_partition}
     else
-        mainPartitionUuid=$(blid ${chosen_partion})
+        mainPartitionUuid=$(blkid ${chosen_partion})
 	if [ SWAPUSED = 0 ]; then
-	    swapPartitionUuid=$(blid ${swap_partion})
+	    swapPartitionUuid=$(blkid ${swap_partion})
         fi
-        efiPartitionUuid=$(blid ${efi_partion})
-	mkfs.vfat ${efi_partition}
-	echo -e "t\n\nuefi\nw" | fdisk ${efi_partition}
+        efiPartitionUuid=$(blkid ${efi_partion})
+	if [[ "$efi_partition" =~ [0-9]$ ]]; then
+  	     efi_device=$(echo "$efi_partition" | sed 's/[0-9]*$//')
+  	     efi_partition_number=$(echo "$efi_partition" | grep -o '[0-9]*$')
+
+  	     (
+ 	     echo "t" 
+ 	     echo "${efi_artition_number}"  
+  	     echo "1"  
+             echo "w"   
+             ) | sudo fdisk "${efi_device}"
+  	     log "The partition ${efi_partition} has been set to EFI System Partition."
+
+	else
+              (
+              echo "n"   
+              echo "p"   
+              echo "1"   
+              echo       
+              echo       
+              echo "t" 
+              echo "1" 
+              echo "w"
+              ) | sudo fdisk "${efi_partition}"
+ 	      log "An EFI partition has been created on the device ${efi_partition}."
+	fi
         mkdir /mnt/efi
-	mount ${efi_partition} /mnt/efi
-        grub-install ${efi_partition} --root-directory=/mnt/efi --target=x86_64-efi --removable
+	mount "${efi_partition}1" "/mnt/efi"
+        grub-install "${efi_partition}1" --root-directory=/mnt/efi --target=x86_64-efi --removable
 	rm -f "${efi_partition}/boot/grub/grub.cfg"
     fi
-    rm -rf /mnt/install/boot/grub/grub.cfg
-    rm -rf /mnt/efi/boot/grub/grub.cfg
-    touch /mnt/install/boot/grub/grub.cfg
-    touch /mnt/efi/boot/grub/grub.cfg
+    rm -rf "/mnt/install/boot/grub/grub.cfg"
+    rm -rf "/mnt/efi/boot/grub/grub.cf"
+    touch "/mnt/install/boot/grub/grub.cfg"
+    touch "/mnt/efi/boot/grub/grub.cfg"
     chosen_partition_suffix="${chosen_partition#/dev/sd}"
     chosen_partition_letter="${chosen_partition_suffix:0:1}"
     grubrootnum0=$(( $(printf "%d" "'${chosen_partition_letter}") - 96 ))
     grubrootnum1="${chosen_partition_suffix:1}"
-    echo "set default=0" >> /mnt/efi/boot/grub/grub.cfg
-    echo "set timeout=5" >> /mnt/efi/boot/grub/grub.cfg
-    echo "" >> /mnt/efi/boot/grub/grub.cfg
-    echo "insmod part_gpt" >> /mnt/efi/boot/grub/grub.cfg
-    echo "insmod ext2" >> /mnt/efi/boot/grub/grub.cfg
-    echo "set root=(hd${grubrootnum0},${grubrootnum1})" >> /mnt/efi/boot/grub/grub.cfg
-    echo "" >> /mnt/efi/boot/grub/grub.cfg
-    echo "insmod all_video" >> /mnt/efi/boot/grub/grub.cfg
-    echo "if loadfont /boot/grub/fonts/unicode.pf2; then" >> /mnt/efi/boot/grub/grub.cfg
-    echo "  terminal_output gfxterm" >> /mnt/efi/boot/grub/grub.cfg
-    echo "fi" >> /mnt/efi/boot/grub/grub.cfg
-    echo "" >> /mnt/efi/boot/grub/grub.cfg
-    echo 'menuentry "GNU/Linux, CydraLite Release V2.0"  {' >> /mnt/efi/boot/grub/grub.cfg
-    echo "  linux   /boot/os root=UUID=${mainPartitionUuid} ro" >> /mnt/efi/boot/grub/grub.cfg
-    echo "}" >> /mnt/efi/boot/grub/grub.cfg
-    echo "" >> /mnt/efi/boot/grub/grub.cfg
-    echo "menuentry "Firmware Setup" {" >> /mnt/efi/boot/grub/grub.cfg
-    echo "  fwsetup" >> /mnt/efi/boot/grub/grub.cfg
-    echo "}" >> /mnt/efi/boot/grub/grub.cfg
+    echo "set default=0" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "set timeout=5" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "insmod part_gpt" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "insmod ext2" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "set root=(hd${grubrootnum0},${grubrootnum1})" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "insmod all_video" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "if loadfont /boot/grub/fonts/unicode.pf2; then" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "  terminal_output gfxterm" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "fi" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo 'menuentry "GNU/Linux, CydraLite Release V2.0"  {' >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "  linux   /boot/os root=UUID=${mainPartitionUuid} ro" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "}" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "menuentry "Firmware Setup" {" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "  fwsetup" >> "/mnt/efi/boot/grub/grub.cfg"
+    echo "}" >> "/mnt/efi/boot/grub/grub.cfg"
 }
 
 #		CYDRA INSTALLATION		#
@@ -264,8 +319,8 @@ function INSTALL_CYDRA {
     cp -r "/mnt/temp/*" "/mnt/install"
     rm -f /mnt/install/etc/fstab
     touch /mnt/install/etc/fstab
-    echo "#CydraLite FSTAB File, Make a backup if you want to modify this file." > /mnt/install/etc/fstab
-    echo "" > /mnt/install/etc/fstab
+    echo "#CydraLite FSTAB File, Make a backup if you want to modify it.." >> /mnt/install/etc/fstab
+    echo "" >> /mnt/install/etc/fstab
     echo "UUID=${mainPartitionUuid}     /            ext4    defaults            1     1" >> /mnt/install/etc/fstab
     if [ SWAPUSED = 0 ]; then
 	echo "UUID=${swapPartitionUuid}     swap         swap     pri=1               0     0" >> /mnt/install/etc/fstab
@@ -278,19 +333,15 @@ function INSTALL_CYDRA {
     if [[ ${WIRELESS} = 1 ]]; then
 	mv "/root/installdir/25-wireless.network" "/mnt/install/systemd/network/25-wireless.network"
     fi
-
-    echo ${password_encrypted} >> "/mnt/install/etc/shadow"
-    echo ${username_encrypted} >> "/mnt/install/etc/passwd"
-    echo "${username}:${password_only}:2130:" >> "/mnt/install/etc/group"
-
-    mkdir "/mnt/install/home/${username}"
-    chown --recursive ${username}:${username} "/mnt/install/home/${username}"
+    rm -f "/mnt/install/etc/wpa_supplicant.conf"
+    cp -r "/etc/wpa_supplicant.conf /mnt/install/etc/wpa_supplicant.conf"
+    
 }
 
 #		INIT SWAP		#
 
 function INIT_SWAP {
-    mkswap ${chosen_swap}
+    mkswap -f ${chosen_swap}
 }
 
 #		CLEAN UP		#
@@ -298,9 +349,9 @@ function INIT_SWAP {
 function CLEAN_LIVE {
     section "CLEANING LIVECD BEFORE REBOOTING"
 
-    umount /mnt/install > /dev/null 2>&1;
-    umount /mnt/efi > /dev/null 2>&1;
-    umount /mnt/temp > /dev/null 2>&1;
+    umount "/mnt/install" > /dev/null 2>&1;
+    umount "/mnt/efi" > /dev/null 2>&1;
+    umount "/mnt/temp" > /dev/null 2>&1;
 }
 
 
@@ -315,21 +366,20 @@ function main {
 	DISK_PARTITION
 
 
-	# If the user wants to continue the installation or return to the beginning
-	if dialog --yesno "Installation will start, do you want to continue ?" 15 75 --stdout; then
+	if dialog --yesno "The Installation will start. Continue?" 25 85 --stdout; then
 
-		# If any field was left blank
-		if [[ -z "${password}" || -z "${language}" || -z "${machine_name}" || -z "${chosen_partition}" ]]; then
+		if [[ -z "${password}" || -z "${username}" || -z "${machine_name}" || -z "${chosen_partition}" ]]; then
 			err  "$@"
-                        main "$@"
+                        /usr/bin/install
 		elif [[ ${WIRELESS} = 1 ]]; then
                      if [[ -z "${network_name}" || -z "${network_password}" ]]; then
         		     err  "$@"
-                             main "$@"
+                             /usr/bin/install
                      fi	
                 else
        			log "installation on '${chosen_partition}'"
-	                if dialog --yesno "!! WARNING !! \n\n EVERY DATA ON THE DISK WILL BE ERASED.\n Do you want to continue ?" 25 85 --stdout; then
+	                if dialog --yesno "!! WARNING !! \n\nEVERY DATA ON THE DISK WILL BE ERASED.\nDo you want to continue ?" 25 85 --stdout; then
+		             mkdir -p ""
             		     DISK_INSTALL
 		   	     GRUB_CONF
             		     INSTALL_CYDRA
@@ -339,9 +389,23 @@ function main {
 	     		     dialog --msgbox "Installation is finished, thanks for using CydraOS !" 0 0
 	                else
   			     if dialog --yesno "Do you want to exit the Installation ?" 15 35 --stdout; then
-			          main "$@"
+	                          stty -echo
+	                          export PS1="Exiting system..."
+			          clear
+			          halt
                              else
-                                  halt
+			          log "Cleaning the vars.."
+	                          sleep 1
+	                          unset "IS_EFI"
+			          unset "SWAPUSED"
+	                          unset "CORRECTDISK"
+			          unset "OLD_PASSWORD"
+	                          unset "partition_list"
+			          unset "WIRELESS"
+	                          unset "AVAILIBLE_LANGUAGES"
+			          log "vars cleaned, restarting installation.."
+			          sleep 2
+                                  /usr/bin/install
 	                     fi
                         fi
 			exit 0
