Update cydramanager

diff --git a/testing/packagemanagers/software/cydramanager b/testing/packagemanagers/software/cydramanager
--- a/testing/packagemanagers/software/cydramanager
+++ b/testing/packagemanagers/software/cydramanager
@@ -517,14 +517,42 @@ function check_fupdatedisk {
 
   > "/etc/cydraterms/firstupdate.log"
 
+  wget "${CORE_DL_URL}" -P ${CACHE_FILE} --no-check-certificate -q
+  tar xf ${CACHE_FILE}/core.db.tar.gz -C ${CACHE_FILE} > /dev/null 2>&1;
+
   UPDATESOFTWARE_MSIZE=0
 
-  find "$CACHE_FILE" -type f -name "*.desc" | while read -r desc_file; do
+  find "$DEST_DIR" -type f -name "*.desc" | while read -r desc_file; do
       ISIZE=$(sed -n '/%ISIZE%/{n;p}' "$desc_file")
-      ISIZE=$(echo "scale=6; $ISIZE / 1024 * 1024" | bc)
       if [ -n "$ISIZE" ]; then
-        UPDATESOFTWARE_MSIZE=$((UPDATESOFTWARE_MSIZE + ISIZE))
-        echo "$(basename "$desc_file") $ISIZE Ko" >> /etc/cydraterms/firstupdate.log
+          UPDATESOFTWARE_MSIZE=$((UPDATESOFTWARE_MSIZE + ISIZE))
+      fi
+  done
+
+  UPDATESOFTWARE_MSIZE=$(( UPDATESOFTWARE_MSIZE / 1024 ))
+
+  USERDISK_MAXSIZE=$(df --output=avail / | tail -n 1)
+  USERDISK_MAXSIZE=$(( USERDISK_MAXSIZE / 1024 ))
+  
+  USAGE_SIZE=$(du -sm /usr | cut -f1)
+
+  TOTAL_REQUIRED_SPACE=$((UPDATESOFTWARE_MSIZE + (2 * USAGE_SIZE)))
+
+  if (( TOTAL_REQUIRED_SPACE > USERDISK_MAXSIZE )); then
+      echo -e "${RED}Votre système manque d'espace disque pour installer la mise à jour..${NC}"
+      rm -rf /etc/cydramanager
+      exit 1
+  else
+      echo -DEST_DIR="/etc/cydramanager/cache"
+
+  > "/etc/cydraterms/firstupdate.log"
+
+  UPDATESOFTWARE_MSIZE=0
+  
+  find "$DEST_DIR" -type f -name "*.desc" | while read -r desc_file; do
+      ISIZE=$(sed -n '/%ISIZE%/{n;p}' "$desc_file")
+      if [ -n "$ISIZE" ]; then
+          UPDATESOFTWARE_MSIZE=$((UPDATESOFTWARE_MSIZE + ISIZE))
       fi
   done
 
@@ -535,13 +563,16 @@ function check_fupdatedisk {
 
   USAGE_SIZE=$(du -sm /usr | cut -f1)
 
-  if (( UPDATESOFTWARE_MSIZE + USAGE_SIZE > USERDISK_MAXSIZE )); then
+  TOTAL_REQUIRED_SPACE=$((UPDATESOFTWARE_MSIZE + (2 * USAGE_SIZE)))
+
+  if (( TOTAL_REQUIRED_SPACE > USERDISK_MAXSIZE )); then
       echo -e "${RED}Votre système manque d'espace disque pour installer la mise à jour..${NC}"
       rm -rf /etc/cydramanager
       exit 1
   else
-      echo -e "${NC}Espace disque nécessaire pour la mise à jour: ${UPDATESOFTWARE_MSIZE}Mo"
+      echo -e "${NC}Espace disque nécessaire pour la mise à jour: ${TOTAL_REQUIRED_SPACE} Mo"
   fi
+  rm -rf "/etc/cydramanager/cache/*"
 }
 
 
